################################################################################
#       Setting dont_touch and dont_use preserve setting
################################################################################
catch {set_db module:lp_riscv_top/ioring .dont_touch true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST0 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST1 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST10 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST11 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_DECLONE_HIER_INST .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST13 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST14 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST15 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST16 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST17 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST18 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST19 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST2 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST20 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST21 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST22 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST23 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST24 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST25 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST26 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST27 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST28 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST29 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST3 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST30 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST31 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST32 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST33 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST34 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST35 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST36 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST37 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST38 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST39 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST4 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST40 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST41 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST42 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST43 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST44 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST45 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST46 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST47 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST48 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST49 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST5 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST50 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST51 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST52 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST53 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST54 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST55 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST57 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST6 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST7 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST8 .dont_touch_hports true}
catch {set_db hinst:lp_riscv_top/lp_riscv/RC_CG_HIER_INST9 .dont_touch_hports true}
